---
output: pdf_document
---
# Developoing Data Products: Quiz 2
Marcos Gestal  


---


### Question 1

In the slidify YAML text. Changing the framework from ```io2012``` to ```shower``` does what?

* It changes the ability to display mathjax javascript rendering.
* It changes nothing.
* ***It changes the html5 framework thus changing the style of the slides.***
* It changes whether the document is self contained or requires being connected to the internet.

### Solution

* ***It changes the html5 framework thus changing the style of the slides.***


### Question 2

You wrote R code in a slidify document as follows (within a R chunk)

```
fit <- lm(y ~ x1 + x2 + x3)
summary(fit)
```

If you want to hide the results of the ```summary``` statement (yet still have it run) what should you do?

* Comment the command as below but also use a bang symbol after the comment, as in #! summary(fit)
* Add a echo = FALSE option in the {r} call of the code chunk
* ***Add a results = 'hide' option in the {r} call of the code chunk***
* Comment out the command # summary(fit)

### Solution

* ***Add a results = 'hide' option in the {r} call of the code chunk***


### Question 3

You wrote R code in a slidify document as follows (within a R chunk)

```
fit <- lm(y ~ x1 + x2 + x3)
summary(fit)
```

* Comment out the command # summary(fit)
* ***Add a echo = FALSE option in the {r} call of the code chunk***
* Add a echo = TRUE option in the {r} call of the code chunk
* Comment the command, but use a bang symbol after the comment, as in #! summary(fit)


### Answer

* ***Add a echo = FALSE option in the {r} call of the code chunk***


###  Question 4

R studio presentation tool does what?

* Creates a presentation that can only be run from within Rstudio
* Creates a power point presentation from a generalized markdown format having an extension Rpres		
* ***Creates HTML5 slides using a generalized markdown format having an extention Rpres and creates reproducible presentations by embedding and running the R code from within the presentation document***
* Creates presentable R code from within presentations. However, it does not actually run the code


### Answer

* ***Creates HTML5 slides using a generalized markdown format having an extention Rpres and creates reproducible presentations by embedding and running the R code from within the presentation document.***  


### Question 5

In Rstudio presenter, if you do not want the code to be evaluated, what option do you need to add to the {r} options?

* ***eval = FALSE***
* run = FALSE
* echo = FALSE
* results = 'hide'

### Solution

* ***eval = FALSE***	


### Question 5

When presenting data analysis to a broad audience, which of the following should be done?

* ***Make the figure axes readable.***
* Do not include figure captions.
* Present results in the chronological order in which it was performed.	
* Show every analysis and method that was done.

### Solution

* ***Make the figure axes readable.***  

